/*
Copyright 2020 Adobe. All rights reserved.
This file is licensed to you under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License. You may obtain a copy
of the License at http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under
the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
OF ANY KIND, either express or implied. See the License for the specific language
governing permissions and limitations under the License.
*/

import * as kit from '@adobe/griffon-toolkit';
import schema from '../schemas/mediaCreateTrackerRequest.json';

/**
 * Contains constants and functions for a Media Create Tracker Request Event.
 *
 * The structure for a Media Create Tracker Request Event is as follows:
 * ```
 * {
 *   payload: {
 *     ACPExtensionEventData: {
 *       trackerid: <string>,
 *       event.param: <object>,
 *     },
 *     ACPExtensionEventSource: 'com.adobe.eventsource.media.requesttracker'
 *     ACPExtensionEventType: 'com.adobe.eventtype.media'
 *     ACPExtensionEventName: <string>,
 *     ACPExtensionEventNumber: <integer>,
 *     ACPExtensionEventUniqueIdentifier: <string>,
 *   },
 *   type: 'generic'
 *   vendor: <string>,
 *   annotations: <array>,
 *   clientId: <string>,
 *   timestamp: <number>,
 *   uuid: <string>,
 * }
 * ```
 *
 * @namespace mediaCreateTrackerRequest
 */

/**
 * Paths for the keys on a Media Create Tracker Request Event
 *
 * @enum {string}
 */
const path = {
  /** An object with custom data describing the event.<br />Path is `payload`. */
  payload: 'payload',

  /** An object with the custom data describing the event.<br />Path is `payload.ACPExtensionEventData`. */
  eventData: 'payload.ACPExtensionEventData',

  /** The unique tracker ID.<br />Path is `payload.ACPExtensionEventData.trackerid`. */
  trackerId: 'payload.ACPExtensionEventData.trackerid',

  /** Information about the event based on the event type.<br />Path is `payload.ACPExtensionEventData."event.param"`. */
  eventParams: 'payload.ACPExtensionEventData."event.param"',

  /** The event source.<br />Path is `payload.ACPExtensionEventSource`. */
  eventSource: 'payload.ACPExtensionEventSource',

  /** The event type.<br />Path is `payload.ACPExtensionEventType`. */
  eventType: 'payload.ACPExtensionEventType',

  /** The name of the event.<br />Path is `payload.ACPExtensionEventName`. */
  eventName: 'payload.ACPExtensionEventName',

  /** The event number generated by the SDK.<br />Path is `payload.ACPExtensionEventNumber`. */
  sdkEventNumber: 'payload.ACPExtensionEventNumber',

  /** The unique event id.<br />Path is `payload.ACPExtensionEventUniqueIdentifier`. */
  eventId: 'payload.ACPExtensionEventUniqueIdentifier',

  /** The type of event.<br />Path is `type`. */
  rootType: 'type',

  /** The vendor of the plugin that sent the event.<br />Path is `vendor`. */
  vendor: 'vendor',

  /** Array of Annotation objects.<br />Path is `annotations`. */
  annotations: 'annotations',

  /** A unique id that differentiates clients from one another.<br />Path is `clientId`. */
  clientId: 'clientId',

  /** When the event occurred.<br />Path is `timestamp`. */
  timestamp: 'timestamp',

  /** Uniquely identifies each event.<br />Path is `uuid`. */
  rootId: 'uuid'
};

/**
 * Describes the number of parents this object has based off schema references. When checking for matches for example, we want to
 * use a schema that is more specific over a more generic schema
 *
 * @constant
 */
const parentDepth = 2;

/**
 * A label that can be used when describing this object
 */
const label = 'Media Create Tracker Request Event';

/**
 * A grouping for this object
 */
const group = 'event';

/**
 * The value for `eventSource` for a Media Create Tracker Request Event.
 *
 * Path is `payload,ACPExtensionEventSource`.
 *
 * @constant
 */
const EVENT_SOURCE = 'com.adobe.eventsource.media.requesttracker';

/**
 * The value for `eventType` for a Media Create Tracker Request Event.
 *
 * Path is `payload,ACPExtensionEventType`.
 *
 * @constant
 */
const EVENT_TYPE = 'com.adobe.eventtype.media';

/**
 * The value for `rootType` for a Media Create Tracker Request Event.
 *
 * Path is `type`.
 *
 * @constant
 */
const ROOT_TYPE = 'generic';

/**
 * Retrieves a value from the object. You can provide either a path or an alias.
 *
 * @function
 * @param {string} alias Path or alias
 * @param {*} data Data to search
 * @returns {*}
 */
const get = (alias, data) => {
  const func = (data2) => kit.search(path[alias] || alias, data2);
  if (!data) { return func; }
  return func(data);
};

/**
 * Returns the `trackerId` from the Media Create Tracker Request Event.
 * This is the the unique tracker ID.
 *
 * Path is `payload,ACPExtensionEventData,trackerid`.
 *
 * @function
 * @param {object} source The Media Create Tracker Request Event instance
 * @returns {string}
 */
const getTrackerId = kit.search(path.trackerId);

/**
 * Returns the `eventParams` from the Media Create Tracker Request Event.
 * This is the information about the event based on the event type.
 *
 * Path is `payload,ACPExtensionEventData,event.param`.
 *
 * @function
 * @param {object} source The Media Create Tracker Request Event instance
 * @returns {object}
 */
const getEventParams = kit.search(path.eventParams);

/**
 * Returns the data using the specified path from the eventParams
 * of the Media Create Tracker Request Event.
 *
 * @function
 * @param {...string} path key in object
 * @param {object} source The Media Create Tracker Request Event instance
 * @returns {*}
 */
const getEventParamsKey = kit.curry(
  (searchPath, source) => kit.search(`${path.eventParams}.${searchPath}`, source)
);

/**
 * Matcher can be used to find matching Media Create Tracker Request Event objects.
 *
 * @see kit.match
 * @constant
 */
const matcher = kit.combineAll([
  'payload.ACPExtensionEventSource==`com.adobe.eventsource.media.requesttracker`',
  'payload.ACPExtensionEventType==`com.adobe.eventtype.media`',
  'timestamp'
]);

/**
 * Tests the provided source against the matcher to see if it's Media Create Tracker Request Event event.
 *
 * @function
 * @param {object} source The Media Create Tracker Request Event instance
 * @returns {boolean}
 * @see kit.isMatch
 */
const isMatch = (source) => kit.isMatch(matcher, source);
/**
 * Generates a Media Create Tracker Request Event with the const values set.
 * Can be useful in testing.
 * Can provide additional data by providing a flat object of paths and values.
 *
 * @function
 * @param {...Function} input Overrides
 * @returns {object}
 */
const make = (input) => kit.expandWithPaths(path, {
  eventSource: 'com.adobe.eventsource.media.requesttracker',
  eventType: 'com.adobe.eventtype.media',
  rootType: 'generic',
  ...input
});

/**
 * Generates a Media Create Tracker Request Event with some default values set.
 * Can be useful in testing.
 * Can override defaults and provide additional data by providing a flat object
 * of paths and values.
 *
 * @function
 * @param {...Function} input Overrides
 * @returns {object}
 */
const mock = (input) => kit.expandWithPaths(path, {
  trackerId: 'trackerId123',
  eventSource: 'com.adobe.eventsource.media.requesttracker',
  eventType: 'com.adobe.eventtype.media',
  rootType: 'generic',
  vendor: 'com.adobe.mobile.sdk',
  clientId: 'appleABC',
  timestamp: Date.parse('12 Jan 2020 07:23:17 GMT'),
  rootId: '123',
  ...input
});

/* ADD CUSTOM CONTENT BELOW */

// additional exports should be added here:
const customExports = {};

/* END CUSTOM CONTENT */
/* The content below is autogenerated. Do not make any changes */

export default {
  path,
  mock,
  make,
  schema,
  get,
  ...customExports,
  getTrackerId,
  getEventParams,
  getEventParamsKey,
  isMatch,
  matcher,
  EVENT_SOURCE,
  EVENT_TYPE,
  ROOT_TYPE,
  label,
  group,
  parentDepth
};
