/*
Copyright 2020 Adobe. All rights reserved.
This file is licensed to you under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License. You may obtain a copy
of the License at http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under
the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
OF ANY KIND, either express or implied. See the License for the specific language
governing permissions and limitations under the License.
*/

import * as kit from '@adobe/griffon-toolkit';
import schema from '../schemas/propositionsRequest.json';

/**
 * Contains constants and functions for a Get Propositions Request.
 *
 * The structure for a Get Propositions Request is as follows:
 * ```
 * {
 *   payload: {
 *     ACPExtensionEventData: {
 *       getpropositions: 'true'
 *       surfaces: <array>,
 *     },
 *     ACPExtensionEventSource: 'com.adobe.eventsource.requestcontent'
 *     ACPExtensionEventType: 'com.adobe.eventtype.messaging'
 *     ACPExtensionEventName: <string>,
 *     ACPExtensionEventNumber: <integer>,
 *     ACPExtensionEventUniqueIdentifier: <string>,
 *   },
 *   vendor: 'com.adobe.griffon.mobile'
 *   type: 'generic'
 *   annotations: <array>,
 *   clientId: <string>,
 *   timestamp: <number>,
 *   uuid: <string>,
 * }
 * ```
 *
 * @namespace propositionsRequest
 */

/**
 * Paths for the keys on a Get Propositions Request
 *
 * @enum {string}
 */
const path = {
  /** An object with custom data describing the event.<br />Path is `payload`. */
  payload: 'payload',

  /** An object with the custom data describing the event.<br />Path is `payload.ACPExtensionEventData`. */
  eventData: 'payload.ACPExtensionEventData',

  getpropositions: 'payload.ACPExtensionEventData.getpropositions',

  /** The list of surfaces propositions were requested for.<br />Path is `payload.ACPExtensionEventData.surfaces`. */
  surfaces: 'payload.ACPExtensionEventData.surfaces',

  /** The event source.<br />Path is `payload.ACPExtensionEventSource`. */
  eventSource: 'payload.ACPExtensionEventSource',

  /** The event type.<br />Path is `payload.ACPExtensionEventType`. */
  eventType: 'payload.ACPExtensionEventType',

  /** The name of the event.<br />Path is `payload.ACPExtensionEventName`. */
  eventName: 'payload.ACPExtensionEventName',

  /** The event number generated by the SDK.<br />Path is `payload.ACPExtensionEventNumber`. */
  sdkEventNumber: 'payload.ACPExtensionEventNumber',

  /** The unique event id.<br />Path is `payload.ACPExtensionEventUniqueIdentifier`. */
  eventId: 'payload.ACPExtensionEventUniqueIdentifier',

  /** The vendor of the plugin that sent the event.<br />Path is `vendor`. */
  vendor: 'vendor',

  /** The type of event.<br />Path is `type`. */
  rootType: 'type',

  /** Array of Annotation objects.<br />Path is `annotations`. */
  annotations: 'annotations',

  /** A unique id that differentiates clients from one another.<br />Path is `clientId`. */
  clientId: 'clientId',

  /** When the event occurred.<br />Path is `timestamp`. */
  timestamp: 'timestamp',

  /** Uniquely identifies each event.<br />Path is `uuid`. */
  rootId: 'uuid'
};

/**
 * Describes the number of parents this object has based off schema references. When checking for matches for example, we want to
 * use a schema that is more specific over a more generic schema
 *
 * @constant
 */
const parentDepth = 2;

/**
 * The name of this event. Same as the file name
 */
const uniqueName = 'propositionsRequest';

/**
 * The package of this event
 */
const packageName = 'aep-mobile';

/**
 * The unique name of this event
 */
const label = 'Get Propositions Request';

/**
 * A grouping for this object
 */
const group = 'event';

/**
 * The value for `getpropositions` for a Get Propositions Request.
 *
 * Path is `payload,ACPExtensionEventData,getpropositions`.
 *
 * @constant
 */
const GETPROPOSITIONS = true;

/**
 * The value for `eventSource` for a Get Propositions Request.
 *
 * Path is `payload,ACPExtensionEventSource`.
 *
 * @constant
 */
const EVENT_SOURCE = 'com.adobe.eventsource.requestcontent';

/**
 * The value for `eventType` for a Get Propositions Request.
 *
 * Path is `payload,ACPExtensionEventType`.
 *
 * @constant
 */
const EVENT_TYPE = 'com.adobe.eventtype.messaging';

/**
 * The value for `vendor` for a Get Propositions Request.
 *
 * Path is `vendor`.
 *
 * @constant
 */
const VENDOR = 'com.adobe.griffon.mobile';

/**
 * The value for `rootType` for a Get Propositions Request.
 *
 * Path is `type`.
 *
 * @constant
 */
const ROOT_TYPE = 'generic';

/**
 * Retrieves a value from the object. You can provide either a path or an alias.
 *
 * @function
 * @param {string} alias Path or alias
 * @param {*} data Data to search
 * @returns {*}
 */
const get = (alias, data) => {
  const func = (data2) => kit.search(path[alias] || alias, data2);
  if (!data) { return func; }
  return func(data);
};

/**
 * Returns the `getpropositions` from the Get Propositions Request.
 * This is the .
 *
 * Path is `payload,ACPExtensionEventData,getpropositions`.
 *
 * @function
 * @param {object} source The Get Propositions Request instance
 * @returns {undefined}
 */
const getGetpropositions = kit.search(path.getpropositions);

/**
 * Returns the `surfaces` from the Get Propositions Request.
 * This is the the list of surfaces propositions were requested for.
 *
 * Path is `payload,ACPExtensionEventData,surfaces`.
 *
 * @function
 * @param {object} source The Get Propositions Request instance
 * @returns {Array}
 */
const getSurfaces = kit.search(path.surfaces);

/**
 * Matcher can be used to find matching Get Propositions Request objects.
 *
 * @see kit.match
 * @constant
 */
const matcher = kit.combineAll([
  'payload.ACPExtensionEventData.getpropositions==`true`',
  kit.combineAny([
    'payload.ACPExtensionEventSource==`com.adobe.eventsource.requestcontent`',
    'payload.ACPExtensionEventSource==`com.adobe.eventsource.requestcontent`'
  ]),
  kit.combineAny([
    'payload.ACPExtensionEventType==`com.adobe.eventtype.messaging`',
    'payload.ACPExtensionEventType==`com.adobe.eventtype.messaging`'
  ]),
  'vendor==`com.adobe.griffon.mobile`',
  'timestamp'
]);

/**
 * Tests the provided source against the matcher to see if it's Get Propositions Request event.
 *
 * @function
 * @param {object} source The Get Propositions Request instance
 * @returns {boolean}
 * @see kit.isMatch
 */
const isMatch = (source) => kit.isMatch(matcher, source);
/**
 * Generates a Get Propositions Request with the const values set.
 * Can be useful in testing.
 * Can provide additional data by providing a flat object of paths and values.
 *
 * @function
 * @param {...Function} input Overrides
 * @returns {object}
 */
const make = (input) => kit.expandWithPaths(path, {
  getpropositions: true,
  eventSource: 'com.adobe.eventsource.requestcontent',
  eventType: 'com.adobe.eventtype.messaging',
  vendor: 'com.adobe.griffon.mobile',
  rootType: 'generic',
  ...input
});

/**
 * Generates a Get Propositions Request with some default values set.
 * Can be useful in testing.
 * Can override defaults and provide additional data by providing a flat object
 * of paths and values.
 *
 * @function
 * @param {...Function} input Overrides
 * @returns {object}
 */
const mock = (input) => kit.expandWithPaths(path, {
  getpropositions: true,
  eventSource: 'com.adobe.eventsource.requestcontent',
  eventType: 'com.adobe.eventtype.messaging',
  vendor: 'com.adobe.griffon.mobile',
  rootType: 'generic',
  clientId: 'appleABC',
  timestamp: Date.parse('12 Jan 2020 07:23:17 GMT'),
  rootId: '123',
  ...input
});

/* ADD CUSTOM CONTENT BELOW */

// additional exports should be added here:
const customExports = {};

/* END CUSTOM CONTENT */
/* The content below is autogenerated. Do not make any changes */

export default {
  path,
  mock,
  make,
  schema,
  get,
  ...customExports,
  getGetpropositions,
  getSurfaces,
  isMatch,
  matcher,
  GETPROPOSITIONS,
  EVENT_SOURCE,
  EVENT_TYPE,
  VENDOR,
  ROOT_TYPE,
  label,
  group,
  parentDepth,
  uniqueName,
  packageName
};
