// TODO: Attach to common base event

/** Payload of a Generic Mobile Event */
export interface MobileEventPayload {
    /** An object with the custom data describing the event */
    ACPExtensionEventData?: object;
    /** The name of the event */
    ACPExtensionEventName?: string;
    /** The event number generated by the SDK */
    ACPExtensionEventNumber?: number;
    /** The event source */
    ACPExtensionEventSource: string;
    /** The event type */
    ACPExtensionEventType: string;
    /** The unique event id */
    ACPExtensionEventUniqueIdentifier?: string;
}

/** Generic Mobile Event */
export interface MobileEvent {
    payload?: MobileEventPayload;
    type: "generic",
    /** The vendor of the plugin that sent the event */
    vendor: string;
}

export enum ACPExtensionEventSource {
    ERRORRESPONSECONTENT = 'com.adobe.eventsource.errorresponsecontent',
    REQUESTCONTENT = 'com.adobe.eventsource.requestcontent',
    RESPONSECONTENT = 'com.adobe.eventsource.responsecontent',
}

export enum ACPExtensionEventType {
    ANALYTICS = 'com.adobe.eventtype.analytics',
    CONFIGURATION = 'com.adobe.eventtype.configuration',
    EDGE = 'com.adobe.eventtype.edge',
}