/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PlacesExit = {
  /**
   * Array of Annotation objects
   */
  annotations?: {
    /**
     * An object with custom data describing the annotation
     */
    payload?: {
      [k: string]: unknown;
    };
    /**
     * This is to scope annotations and prevent overwrites from other plugins. The type is usually determined by the plugin writing the annotation
     */
    type: string;
    /**
     * Uniquely identifies each annotation
     */
    uuid: string;
    [k: string]: unknown;
  }[];
  /**
   * A unique id that differentiates clients from one another
   */
  clientId: string;
  /**
   * An object with custom data describing the event
   */
  payload?: {
    [k: string]: unknown;
  };
  /**
   * When the event occurred
   */
  timestamp: number;
  /**
   * The type of event
   */
  type: "blob" | "client" | "control" | "generic" | "log" | "status";
  /**
   * Uniquely identifies each event
   */
  uuid: string;
  [k: string]: unknown;
} & {
  payload?: {
    ACPExtensionEventData: {
      /**
       * The POI that the user exited
       */
      triggeringregion: {
        /**
         * The POI latitude
         */
        latitude: number;
        /**
         * The Places library the POI belongs to
         */
        libraryid: string;
        /**
         * The POI longitude
         */
        longitude: number;
        /**
         * The POI name
         */
        regionname?: string;
        /**
         * An object with some defined items and custom data items.
         */
        regionmetadata?: {
          /**
           * The POI category
           */
          category?: string;
          /**
           * The POI city
           */
          city?: string;
          /**
           * The POI country
           */
          country?: string;
          /**
           * The POI state
           */
          state?: string;
          /**
           * The POI street
           */
          street?: string;
          [k: string]: unknown;
        };
        /**
         * The POI radius
         */
        radius: number;
        /**
         * The unique region id
         */
        regionid: string;
        /**
         * Is the user currently in the POI
         */
        useriswithin: boolean;
        /**
         * The weight of the POI. It is used to prioritize POIs when a user is inside multiple POIS
         */
        weight: number;
        [k: string]: unknown;
      };
      /**
       * The type of action that took place. In this case it is exit
       */
      regioneventtype: "exit";
      [k: string]: unknown;
    };
    ACPExtensionEventSource?: "com.adobe.eventSource.responseContent";
    [k: string]: unknown;
  };
  [k: string]: unknown;
};
