/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Annotation {
  /**
   * An object with custom data describing the annotation
   */
  payload?: {
    [k: string]: unknown;
  };
  /**
   * This is to scope annotations and prevent overwrites from other plugins. The type is usually determined by the plugin writing the annotation
   */
  type: string;
  /**
   * Uniquely identifies each annotation
   */
  uuid: string;
  [k: string]: unknown;
}
