/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Command {
  /**
   * A unique id that differentiates clients from one another
   */
  clientId?: string;
  /**
   * An object with custom data describing the event
   */
  payload?: {
    [k: string]: unknown;
  };
  /**
   * When the command was triggered
   */
  timestamp: number;
  /**
   * The type of event. For commands it's always 'control'.
   */
  type: "control";
  /**
   * The vendor of the plugin to receive the command
   */
  vendor?: string;
  [k: string]: unknown;
}
