/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NetworkResponse = {
  /**
   * Array of Annotation objects
   */
  annotations?: {
    /**
     * An object with custom data describing the annotation
     */
    payload?: {
      [k: string]: unknown;
    };
    /**
     * This is to scope annotations and prevent overwrites from other plugins. The type is usually determined by the plugin writing the annotation
     */
    type: string;
    /**
     * Uniquely identifies each annotation
     */
    uuid: string;
    [k: string]: unknown;
  }[];
  /**
   * A unique id that differentiates clients from one another
   */
  clientId: string;
  /**
   * An object with custom data describing the event
   */
  payload?: {
    [k: string]: unknown;
  };
  /**
   * When the event occurred
   */
  timestamp: number;
  /**
   * The type of event
   */
  type: "blob" | "client" | "control" | "generic" | "log" | "status";
  /**
   * Uniquely identifies each event
   */
  uuid: string;
  [k: string]: unknown;
} & {
  payload?: {
    /**
     * Whether the data was loaded from the browser cache.
     */
    fromCache?: boolean;
    /**
     * The webpage that initiated the request.
     */
    initiator?: string;
    /**
     * The ip address of the server.
     */
    ip?: string;
    /**
     * Parsed information from the request URL.
     */
    location?: {
      /**
       * The domain portion of the request URL.
       */
      domain?: string;
      /**
       * The hash portion of the request URL.
       */
      hash?: string;
      /**
       * The host portion of the request URL. Includes port number
       */
      host?: string;
      /**
       * The host portion of the request URL without the port number.
       */
      hostname?: string;
      /**
       * The origin portion of the request URL.
       */
      origin?: string;
      /**
       * The path of the request URL.
       */
      path?: string;
      /**
       * The port of the request URL.
       */
      port?: string;
      /**
       * The protocol portion of the request URL.
       */
      protocol?: string;
      /**
       * The query string portion of the request URL.
       */
      query?: string;
      [k: string]: unknown;
    };
    /**
     * HTTP method that the request is made with.
     */
    method?: string;
    /**
     * The headers returned from the server.
     */
    responseHeaders?: {
      [k: string]: unknown;
    };
    /**
     * ID that can be used to pair requests with responses.
     */
    requestId?: string;
    /**
     * The resulting status code of the request.
     */
    statusCode?: number;
    /**
     * More details about the status of the request.
     */
    statusLine?: string;
    /**
     * The URL the request is being made to. Contains the full host, path, and query string.
     */
    url?: string;
    [k: string]: unknown;
  };
  /**
   * The type of event. For network responses it's always 'netres'.
   */
  type: "netres";
  [k: string]: unknown;
};
