/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Poi {
  /**
   * The POI latitude
   */
  latitude: number;
  /**
   * The Places library the POI belongs to
   */
  libraryid: string;
  /**
   * The POI longitude
   */
  longitude: number;
  /**
   * The POI name
   */
  regionname?: string;
  /**
   * An object with some defined items and custom data items.
   */
  regionmetadata?: {
    /**
     * The POI category
     */
    category?: string;
    /**
     * The POI city
     */
    city?: string;
    /**
     * The POI country
     */
    country?: string;
    /**
     * The POI state
     */
    state?: string;
    /**
     * The POI street
     */
    street?: string;
    [k: string]: unknown;
  };
  /**
   * The POI radius
   */
  radius: number;
  /**
   * The unique region id
   */
  regionid: string;
  /**
   * Is the user currently in the POI
   */
  useriswithin: boolean;
  /**
   * The weight of the POI. It is used to prioritize POIs when a user is inside multiple POIS
   */
  weight: number;
  [k: string]: unknown;
}
